# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [1]:
#code here
import numpy as np
arr1 = np.array([1, 1,1, 2, 2, 2, 3, 3, 3, 4, 4, 4])
arr2= arr1.reshape(3, 4)
print(arr2)
array1 = np.array([[1, 1], [1,1]])
array2 = np.array([[2, 2], [2, 2]])
horizontal = np.hstack((array1, array2))
print("horizontally:")
print(horizontal)
vertical = np.vstack((array1, array2))
print("vertically:")
print(vertical)

[[1 1 1 2]
 [2 2 3 3]
 [3 4 4 4]]
horizontally:
[[1 1 2 2]
 [1 1 2 2]]
vertically:
[[1 1]
 [1 1]
 [2 2]
 [2 2]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [5]:
def emailfunction(email):
    important = ["important", "crucial", "vital", "significant", "urgent"]
    promotion = ["deal", "promotion", "promo", "sale", "discount"]
    spam = ["bonus", "gift", "free", "spin", "won"]
    
    i_mail = []
    p_mail = []
    s_mail = []
    
    for mail in email:
        for word in mail.split():  
            for imp_word in important:
                if imp_word in word.lower():
                    i_mail.append(mail)
                    break
            for promo_word in promotion:
                if promo_word in word.lower():
                    p_mail.append(mail)
                    break
            for spam_word in spam:
                if spam_word in word.lower():
                    s_mail.append(mail)
                    break
    print("Important: ", i_mail)
    print("Promotion: ", p_mail)
    print("Spam: ", s_mail)

mails = [
    "important email about your account",
    "Get our latest promotion",
    "You've got a gift! Claim your prize now!",
    "you won a new phone",
    "GIFT!!",
    "urgent : Action required on your subscription",
    "Great deal. check out!",
    "sale!!",
    "vital email: please send your details"
]

emailfunction(mails)


Important:  ['important email about your account', 'urgent : Action required on your subscription', 'vital email: please send your details']
Promotion:  ['Get our latest promotion', 'Great deal. check out!', 'sale!!']
Spam:  ["You've got a gift! Claim your prize now!", 'you won a new phone', 'GIFT!!']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [1]:
#code here
dictionary = {
    "hello": "hola",
    "bye": "adiós",
    "how": "cómo",
    "fine": "bien"
}

def translate_word(word):
    if word in dictionary:
        return dictionary[word]
    else:
        return ("Sorry, can't translate that")

while True:
    user_input = input("Enter an English word. Press 'exit' to close the program: ")
    if user_input.lower() == "exit":
        print("Exiting program. Goodbye!")
        break
    else:
        translation = translate_word(user_input.lower())
        print(f"The Spanish translation is: '{translation}'" )


Enter an English word. Press 'exit' to close the program: h
The Spanish translation is: 'Sorry, can't translate that'
Enter an English word. Press 'exit' to close the program: hello
The Spanish translation is: 'hola'
Enter an English word. Press 'exit' to close the program: bye
The Spanish translation is: 'adiós'
Enter an English word. Press 'exit' to close the program: exit
Exiting program. Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [14]:

import pandas as pd

url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)
df



Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [8]:
#Calculate the total global sales for all games in the dataset.
total_globalsales = df['Global_Sales'].sum()
print(total_globalsales)

8920.44


In [9]:
#Find the game with the highest global sales.
highest = df.loc[df['Global_Sales'].idxmax()]
print(highest)

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [10]:
#Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
average = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print(average)

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [11]:
#Find the top 5 most popular game genres based on global sales.
top5 = df.groupby('Genre')['Global_Sales'].sum()
print(top5.nlargest(5))

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [17]:
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
totall= df.groupby(['Genre'])[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print(totall)
NA= df.groupby('Genre')['NA_Sales'].sum().idxmax()
print("MOST popular in NA: ",NA)

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36
MOST popular in NA:  Action


In [18]:
#Display last 10 rows.
rows = df.tail(10)
print("Last 10 Rows:")
print(rows)

Last 10 Rows:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
1

In [19]:
#Determine the top 3 gaming platforms with the highest global sales.
top_3 = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print(top_3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [23]:
#Calculate the market share (percentage of global sales) for each genre.
market_share = df.groupby('Genre')['Global_Sales'].sum() 
percent=market_share/ total_globalsales * 100
print(percent)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [24]:
#Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print(correlation_coefficient)

0.7677267483702629
